### ISSUE TITLE
window10平台下，安装.exe文件闪退

### ISSUE THREAD

**Issue by lawushanshan** [dcl-lily/IIS-AMP-Monitor#1]
开发者您好，感谢您的开源软件，我这边下载了2.2release版本的.exe文件，在双击打开该文件时，cmd出现一行字，就闪退了，没办法安装，因为时间太短，也没办法截图，请问下，有没有其他的安装方法？

**Comment by dcl-lily** [comment]
这个程序需要给定参数执行，不能直接双击运行了。在CMD下，CD到这个exe执行文件的目录，.check_iis.exe -H

**Comment by lawushanshan** [comment]
好的，感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dcl-lily"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 上午9:30
收件人: "dcl-lily/IIS-AMP-Monitor"<IIS-AMP-Monitor@noreply.github.com&gt;; 
抄送: "】这个朋友不陌生"<564890112@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcl-lily/IIS-AMP-Monitor] window10平台下，安装.exe文件闪退 (#1)





 
这个程序需要给定参数执行，不能直接双击运行了。在CMD下，CD到这个exe执行文件的目录，.check_iis.exe -H

**Comment by dcl-lily** [comment]
需要调用运行，非安装程序
